### ISSUE TITLE
Basic On-Premise Server

### ISSUE THREAD

**Issue by schettn** [snek-at/ops-engine#1]
**User Stories**
- As a company I want to be able to analyze my employees contributions without displaying the results to the public, in order to keep private information private.

**Is your feature request related to a problem? Please describe.**
Many companies want an in-depth analysis of their data. However, they are not ready to publish all of it. By using an on-premis server it is possible to store and illustrate analysis data internally only and to publish (if wanted) a self-defined company page on "https://snek.at/enterprise/COMPANY".

**Describe the solution you'd like**
The red path illustrates the flow for the on-premise server.
![image](https://user-images.githubusercontent.com/55298934/88191342-a1ecaa00-cc3b-11ea-8877-1bbe32f799bd.png)

***Engine - EC - OPS - SITP Workflow Overview***

![image](https://user-images.githubusercontent.com/52858351/88515682-601d8400-cfec-11ea-8a12-4420f78387d7.png)

Solutions that can be implemented:
- Connect with Enterprise Connector (https://github.com/snek-at/ec)
- Database models for:
  + User
  + Company page
  + Data
- API for:
  + Company Page
  + SNEK in the Pipeline
- GQL Client for:
  + SNEK Connector
  + GitLab API
- Configure GitLab:
  + Add User (SNEKman)

**Requirements**
- [x] One-Premise Server Concept. #2  
- [x] Template Repository for Wagtail. #3
- [x] Local GitLab Server for On-Premise Server. #4 
- [x] Update the coding Guideline for Python. https://github.com/snek-at/tonic/issues/6   

**Milestones**
<table>
   <tbody>
      <tr>
         <th align="left" width=200px><b>Feature Milestones</b></th>
         <th align="left" width=250px>Completed at in RFC 2822 format</th>
      </tr>
      <tr>
         <td>Feature Designed</td>
         <td>Thu, 23 Jul 2020 16:25:44 +0200</td>
      </tr>
      <tr>
         <td>Requirements Fulfilled</td>
         <td>Mon, 27 Jul 2020 14:12:42 +0200</td>
      </tr>
      <tr>
         <td>Feature Reviewed</td>
         <td>Mon, 27 Jul 2020 14:14:34 +0200</td>
      </tr>
      <tr>
         <th align="left"><b>Opportunity Milestones</b></th>
         <th align="left">Completed at in RFC 2822 format</th>
      </tr>
      <tr>
         <td>Implementation Done</td>
         <td>Tue, 13 Aug 2020 16:25:00 +0200</td>
      </tr>
      <tr>
         <td>Implementation Reviewed</td>
         <td></td>
      </tr>
      <tr>
         <td>Implementation Deployed</td>
         <td></td>
      </tr>
   </tbody>
</table>
